### ISSUE TITLE
Update to NC 14.0.1: Integrety check fails

### ISSUE THREAD

**Issue by Huster-at-github** [doganoo/RecommendationAssistant#6]
Had no problems with the app on NC 14.0.0
After update to NC 14.0.1 get the following integrety check error:

`Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- recommendation_assistant
	- EXTRA_FILE
		- tests/._.DS_Store

Raw output
==========
Array
(
    [recommendation_assistant] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [tests/._.DS_Store] => Array
                        (
                            [expected] => 
                            [current] => f1e82573db1da08be076ab30e7d8cff350e15d06765e1bb74e313cf5f93e1df6921893a3589df51e6b18538c21a9df6d3f23fead170e9b3c02993f5b5d4a2f4d
                        )

                )

        )

)`

File `/var/www/nextcloud/apps/recommendation_assistant/tests/._.DS_Store` exists.
Uninstall and reinstall does not help.

**Comment by Huster-at-github** [comment]
Deleting
`/var/www/nextcloud/apps/recommendation_assistant/tests/._.DS_Store`
worked.

**Comment by doganoo** [comment]
thank your for opening this issue. I am working on a new release and will fix this issue as well. If your workaround works well then please stay tuned :)

**Comment by doganoo** [comment]
I have released a new version (1.0.2) which should fix this issue. Please update the app
